//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net5Sample {
    using System;
    using Devart.Data.Oracle;

  
  
  public class CustomerTypDemo : Devart.Data.Oracle.ICustomOracleObject {
    
    private bool isNull;
    
    private int customerId;
    
    private string custFirstName;
    
    public CustomerTypDemo() {
    }

    public CustomerTypDemo(int id, string name) {
            this.CustomerId = id;
            this.CustFirstName = name;
    }

    
    public CustomerTypDemo(Devart.Data.Oracle.OracleObject oraObject) {
      this.isNull = oraObject.IsNull;
      if (this.isNull) {
        return;
      }
      object attributeValue;
      attributeValue = oraObject["CUSTOMER_ID"];
      if ((attributeValue == System.DBNull.Value)) {
        this.customerId = 0;
      }
      else {
        this.customerId = Convert.ToInt32(attributeValue);
      }
      attributeValue = oraObject["CUST_FIRST_NAME"];
      if ((attributeValue == System.DBNull.Value)) {
        this.custFirstName = "";
      }
      else {
        this.custFirstName = ((string)(attributeValue));
      }
    }
    
    public bool IsNull {
      get {
        return this.isNull;
      }
      set {
        this.isNull = value;
      }
    }
    
    public int CustomerId {
      get {
        return this.customerId;
      }
      set {
        this.customerId = value;
      }
    }
    
    public string CustFirstName {
      get {
        return this.custFirstName;
      }
      set {
        this.custFirstName = value;
      }
    }
    
    public void FromOracleObject(Devart.Data.Oracle.NativeOracleObject oraObject) {
      this.isNull = oraObject.IsNull;
      if (this.isNull) {
        return;
      }
      object attributeValue;
      attributeValue = oraObject["CUSTOMER_ID"];
      if ((attributeValue == System.DBNull.Value)) {
        this.customerId = 0;
      }
      else {
        this.customerId = Convert.ToInt32(attributeValue);
      }
      attributeValue = oraObject["CUST_FIRST_NAME"];
      if ((attributeValue == System.DBNull.Value)) {
        this.custFirstName = "";
      }
      else {
        this.custFirstName = ((string)(attributeValue));
      }
    }
    
    public Devart.Data.Oracle.NativeOracleObject ToOracleObject(Devart.Data.Oracle.OracleConnection connection) {
      NativeOracleObject oracleObjectOci;
      oracleObjectOci = new NativeOracleObject("SYS.CUSTOMER_TYP_DEMO", connection);
      if (this.isNull) {
        return oracleObjectOci;
      }
      oracleObjectOci["CUSTOMER_ID"] = this.customerId;
      oracleObjectOci["CUST_FIRST_NAME"] = this.custFirstName;
      return oracleObjectOci;
    }
  }
}
