//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net5Sample
{
    using System;
    using System.Data;
    using Devart.Data.Oracle;

    // A custom class mapping to an Oracle collection type.
    public class CustomerTypList : Devart.Data.Oracle.ICustomOracleArray
    {
        // The OracleArrayMapping attribute is required to map .NET class member to Oracle collection type.
        public CustomerTypDemo[] objArticles;
        private NativeOracleObject[] nativeOracleObjects;

        // A private member indicating whether this object is null.
        private bool isNull;

        public CustomerTypList()
        {
        }

        public CustomerTypList(CustomerTypDemo[] objArt)
        {
            this.objArticles = objArt;
            this.nativeOracleObjects = new NativeOracleObject[objArt.Length];
        }

        // A property of interface INullable. Indicate whether the custom type object is null.
        public bool IsNull
        {
            get { return this.isNull; }
        }

        // Static null property is required to return a null UDT.
        public static CustomerTypList Null
        {
            get
            {
                CustomerTypList obj = new CustomerTypList();
                obj.isNull = true;
                return obj;
            }
        }

        public void FromOracleArray(NativeOracleArray oraArray)
        {
            throw new NotImplementedException();
        }

        public NativeOracleArray ToOracleArray(OracleConnection con)
        {
            NativeOracleArray oracleObjectOci;
            oracleObjectOci = new NativeOracleArray("SYS.CUSTOMER_TYP_LIST", con);
            if (this.isNull)
            {
                return oracleObjectOci;
            }

            //oracleObjectOci = (CustomerTypDemo[])this.objArticles;

            int i = 0;
            foreach (var obj in this.objArticles)
            {
                nativeOracleObjects[i] = obj.ToOracleObject(con);
                i++;
            }
            oracleObjectOci.Value = nativeOracleObjects;

            return oracleObjectOci;
        }
    }
}
